### ISSUE TITLE
P-0001: Use always jasypt instance to encrypt passwords

### ISSUE THREAD

**Issue by thewillyhuman** [Arquisoft/Inci_i3a#1]
# Use always jasypt instance to encrypt passwords

* Proposal: P-0001
* Authors: [Guillermo Facundo Colunga](https://github.com/thewilly)
* Review Manager: @Arquisoft/course1718_i3a 
* Status: **Accepted**

## Introduction

In order to all modules to fit together all must share same way to
encrypt / decrypt passwords. [Jasyp](http://www.jasypt.org) was used in [module 2](https://www.github.com/Arquisoft/Agents_i3a) and fits perfectly for our requirements.

## Motivation

As a way to manage security in all the modules they should somehow encrypt the sensible
data before sending it to the database, so sensible data remains encrypted in the database.
As the database is read/written from different modules, all of them should implement the same encrypt / decrypt algorithm. As describen in the introduction [jasyp](http://www.jasypt.org) gives a perfectly easy solution.

## Proposed solution

Change the implementation of the [module 1](https://www.github.com/Arquisoft/Loader_i3a) to support the `jasyp` instance and implement, from now on the `jasyp` as default password manager.

## Detailed proposal

To use [jasyp](http://www.jasypt.org) first step is to import the appropriate type we're gonna use to encrypt/decrypt. Then we will use different methods for encryption and de-cryption. Here are the sentences needed.
 
**Maven dependency:**
```xml
<dependency>
    <groupId>org.jasypt</groupId>
    <artifactId>jasypt</artifactId>
    <version>1.9.2</version>
</dependency>
```
**Import:**
```java
import org.jasypt.util.password.StrongPasswordEncryptor;
```
**Encrypt:**
```java
// scryptedPassword is the password to store in the database and to be set to the agent/user.
String scryptedPassword = new StrongPasswordEncryptor().encryptPassword(password);
```
**Decrypt password:**
```java
// 'password' is the password in plain text introduced by the user/agent.
// getPassword() is the password previously seated, it is encrypted.
Boolean isCorrectPassword = new StrongPasswordEncryptor().checkPassword(password, user.getPassword());
```

## Effect on long-term stability

This change will be a long-term change. If this proposal is approved all following modules or applications that works with this project will need from the `jasyp` library to be able to communicate with the database.

## Alternatives considered

Another alternative could be just storing passwords as plain text in the database but then anyone that gets to the database data can read passwords. (not the most secure one)

**Comment by thewillyhuman** [comment]
@Arquisoft/course1718_i3a please add your review to continue with the process of the proposal.

**Comment by eleallegue** [comment]
We create in the module 1, Loader, a random password in the class PasswordGenerator:

	public static void createPasswords(Set<Agent> census) {
		SecureRandom rnd = new SecureRandom();
		StringBuilder sb = new StringBuilder(passLength);
		for(Agent c: census) {
			for (int i = 0; i < passLength; i++) {
				sb.append(passCharacters
						.charAt(rnd.nextInt(passCharacters.length())));
			}
			c.setPassword(sb.toString());
		}
	}
So, how do I insert the encrypt in our code? Because we don't have a string to pass as a parameter as you described.
And decrypt I guess you refer that we must use it when we send the letter generators.

**Comment by thewillyhuman** [comment]
Yes, `c.setPassword(String newPassword);` uses a string as the new password. So this `newPassword` is the encryptedPassword. In order to encrypt it you can use the StringBuilder of the random password. In pseudocode will be something like:
```Java
StringBuilder sb = //initialize...
// Generate random password over sb 
user.setPassword(new EncryptTypeInstance(sb.toString()));
```

**Comment by eleallegue** [comment]
The Loader module has been changed for adding the encrytion method you have proposed (pull request #31), which I personally think is the best approach for satisfying the quality attribute: Security we have set in our documentation and in our whole project. 

I have included some tests for checking if the method you passed for decrypting worked:
`Boolean isCorrectPassword = new StrongPasswordEncryptor().checkPassword(password, user.getPassword());`

And all the tests are perfect!
