### ISSUE TITLE
Kafka names

### ISSUE THREAD

**Issue by eleallegue** [Arquisoft/Inci_i3a#2]
We need to select a name for the topic of all the messages we will send, or receive, depending on the module we implement.
I propose as the name of the topic, so both the producer and the consumer modules read the same:
**incident**

We also need to decide, if the information we are going to send/receive, will be Strings or JSON. I would rather choose JSON, because we can assign key words to the values inserted, and seems easy to implement in Java. If we decide JSON, we will also have to arrange the key names so that we always read the same information from it.

**Comment by thewillyhuman** [comment]
Hi,
**First**, as the title name was not following the proposal style `P-XXXX: Proposal title`, I removed the proposal tag. Even though, if re-styled to match a proposal template, I would be grateful to include it again in the proposals.

**Second**, and most important. I think the name of the topic fits perfectly the intention of the messages, but maybe making it plural will just turn it a bit more understandable for future developers. As the topic reflects all the _incident**s**_ that are submitted as messages to kafka.

Last, JSON is just the perfect format to pass messages, strings would be more complicated to format and parse.

**Comment by eleallegue** [comment]
Okay, our topic will  be called **incidents** then.
For the JSON format, and parsing the String into a JSON directly, I think that the names should fit with the attributes we have in out Incident.java are:

``` java
  private long id;
  private String name;
  private String description;
  private IncidentStates state;
  private String location;
  private List<String> tags;
  private List<String> multimedia;
  private Map<String, String> property_value;
  private List<String> comments;
```

**Comment by eleallegue** [comment]
En el comentario anterior, falta el attribute:

```
private String name;

```

**Comment by eleallegue** [comment]
Moreover, the Enum used in the state is the following one:

```java
public enum IncidentStates {
	OPEN, IN_PROCESS, CLOSED, CANCELLED;
}

```
