### ISSUE TITLE
CloudKafkara for production

### ISSUE THREAD

**Issue by vicsufer** [Arquisoft/Inci_i3a#3]
A kafka server has been setup for production, the incidence manager module is already using it. The Dahsbourd should be able to consume the topics of this server.

The server can be monitored through [here](https://ark.srvs.cloudkafka.com/).

> Username: csmooqu9
> Password: v81tJqgUGp7ZJngSb4Em16eifeisY8kf
> Topic in use: csmooqu9-incidences

**Comment by thewillyhuman** [comment]
Awesome. Thanks!
