### ISSUE TITLE
P-0002: Migrate to gradle as a dependency manager

### ISSUE THREAD

**Issue by thewillyhuman** [Arquisoft/Inci_i3a#6]
# Migrate to gradle as a dependency manager

* Proposal: P-0002
* Authors: [Guillermo Facundo Colunga](https://github.com/thewilly)
* Review Manager: @Arquisoft/course1718_i3a 
* Status: **Rejected**

## Introduction

In order to implement a good "micro-service" architecture on the modules would be necessary to migrate from maven to gradle. Maven has served us so well for long time, but if we want to implement a truly micro-service architecture in the repositories it's completely necessary to migrate to gradle.

## Motivation

Maven its a really powerful dependency manager solution, but when has to deal with modules does not behave so well.
Also, in order to keep the code clean the micro-services should be implemented in separated "projects", that is not all of them inside the same `src` folder.

## Proposed solution

Start by doing some tests with gradle just to check that can help us to solve the problem found. Once proven that fits our problem begin the implementation phase where small teams will change each 'candidate' repository from maven to gradle.

## Effect on long-term stability

This change will be a long-term change. If this proposal is approved any following module or application that is develop should use as a dependency manager gradle..

## Alternatives considered

_Left that repositories as they are as they work well, but not the best solution._

**Comment by vicsufer** [comment]
How is grade's learning curve? 
We're in a stage of the semester in which the amount of time we have available is quite limited, so the time invested to learn gladle should be considered before making a decision.

**Comment by thewillyhuman** [comment]
I know and that's my deepest concern. Gradle is pretty simple because its has the same ideas as maven but uses groovy instead of XML. 
In fact I offer myself to test it on one of the modules and in the case that the implementation works, teach other members on how to make the same with other modules. Consider this just for an extra mark at the final evaluation.

**Comment by thewillyhuman** [comment]
So, after some tests on how to integrate and migrate from maven to gradle I've discovered that the migration of all services will not be so easy as the "micro-modules" need to be run from an outside main "micro-module" and integration tests on each "micro-module" need a dependency form the root project. Ending on a a mess of project. 

As a resume:
Gradle it's an awesome tool but we need to now how to structure the project in order not to have a mess on the dependencies. From now we will continue with gradle. At least until we know how to run integration tests from each "micro-module".
