### ISSUE TITLE
P-0003: Add an orchestration service to allow dynamic ip allocation for services

### ISSUE THREAD

**Issue by thewillyhuman** [Arquisoft/Inci_i3a#7]
# Migrate to gradle as a dependency manager

* Proposal: P-0003
* Authors: [Guillermo Facundo Colunga](https://github.com/thewilly)
* Review Manager: @Arquisoft/course1718_i3a 
* Status: **Revision Needed**

## Introduction

We already have some micro-services running up, like the authorization one or the rest service to process incidences. Those services sometimes need to make calls between them, to solve that right now we've hardcoded the ip and port of the destination service. This is not a good practice, if we change some ip or port from some service the whole application won't work.

## Proposed solution

Netflix has developed an application called [**Eureka**](https://github.com/Netflix/eureka). This application allow micro-services to register on it and call another services already registered there. So, I think, at least should be considered for implementation.

You can find more information [here](https://medium.com/@tharanganilupul/microservices-implementation-netflix-stack-ba4f4a57a79f)

## Alternatives considered

_Left things as they are. Not the best approach._

**Comment by vicsufer** [comment]
I believe it's a great idea, however it's priority is quite much lower than making the modules works all together (At least with harcoded IPs/Ports/etc)

However as a enhancement of the final product it will be a great feature.

**Comment by thewillyhuman** [comment]
Yes sure!

Just to point how easy to do is I take the freedom to implement a kind of skeleton on the [InciManager](https://www.github.com/Arquisoft/InciManager_i3a). You can find the control panel [here](http://eureka-i3a.herokuapp.com).
