### ISSUE TITLE
Test Upload

### ISSUE THREAD

**Issue by vicsufer** [Arquisoft/Inci_i3a#8]
We need to decide where to upload the test for the different tests, grafana, cucumber, etc.

**Comment by vicsufer** [comment]
I believe the best option is upload any gatlin test to this repository, in this way we can run every single test at once. Or even setup them in machine an use cron or whatever to run them periodically.

**Comment by thewillyhuman** [comment]
Okay upload them wherever you decide, if we need to move them in the future won't be a huge problem

**Comment by vicsufer** [comment]
Only user-files will be part of version control since this folder contains unique source necessary to run simulations.
Once cloned, except user-files the rest of directories in the gatling folder downloaded from the official page may be copy  over the Gatlin folder inside the cloned repository. This allow us to avoid copy-pasting scenarios from our repository to gatling folder without messing the version control.
